### ISSUE TITLE
Move 'Open Mail' separately from 'Inbox'

### ISSUE THREAD

**Issue by tuftelien** [the-rebel-Mermaid/BlizzMove#30]
Currently the frame for an open mail is locked to being at the right side of the inbox.

Being able to unlock this anchor would be nice, though I don't know if there's a technical limitation to this.

(Classic)

**Comment by Numynum** [comment]
we're looking into it, but hitting a few obstacles for now
the open mail frame interacts differently to most other frames, and likes to cause errors

**Comment by Numynum** [comment]
feel free to test this in the latest BlizzMove alpha release, and report any issues you come across

**Comment by Numynum** [comment]
we made some changes that should now be downloadable from twitch client/curse
due to how ElvUI handles the frame, we changed the openmailframe to be a childframe of the main mail frame; so you can detach/reattach the frame with ALT+left/right-click

let us know if there's any other issues with the frame
